version: '3.8'

services:
  homeassistant:
    container_name: homeassistant-dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # Mount local config directory
      - ./config:/config
      # Mount the custom component for live development
      - ./custom_components:/config/custom_components
    environment:
      - TZ=America/Vancouver
    restart: unless-stopped
    ports:
      - "8123:8123"
